mkdir order-service
cd order-service

go mod init order-service

go get github.com/gin-gonic/gin

go mod tidy - download required packages

go build - build the application and create an executable file

go mod tidy
go build
go test ./...
go run main.go
